services:
  - type: web
    name: question-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c 'source venv/bin/activate && gunicorn question_ai.wsgi:application'
    envVars:
      - key: HUGGINGFACE_API_TOKEN
        sync: false
