services:
  - type: web
    name: question-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn question_ai.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: question_ai.settings

