    services:
  - type: web
    name: question-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: >
      python manage.py migrate &&
      gunicorn question_ai.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: projet_eglise_db
          property: connectionString
 

