services:
  - type: web
    name: question-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn question_ai.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
  - key: HUGGINGFACE_API_TOKEN
    sync: false
